version: "3.8"

services:
  order_service_db:
    image: mysql:8.0
    container_name: product_service_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: product_service_db
    ports:
      - "3309:3306"
    volumes:
      - /home/kirsenko/docker/mysql/product_service_db:/var/lib/mysql